### ISSUE TITLE
Define Forestry Data Fix - Pattern 1 (Jenkins)

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/fsa2#57]
* implement a simple datafix for Anne Marie using the on prem. Jenkins cron service.

First attempt of this task Consists of:
1. Getting the scripts that Anne Marie runs
1. Putting scripts into a github / or other repo (includes parameterize / extraction of any data that might be private (db link names as an example)
1. Create a jenkinsfile that will run the scripts

* long term think about running this work in Openshift as a cron job and pipe the results / logs to the observability stack

**Comment by amee99073** [comment]
We need the queries to determine if bad data exists, and the scripts to run to correct the data.
The first attempt will be a very simply find records where value = Y and date < sydate-1day. For all records returned, set the Y to N
The rest are a little bit more complex but there's another one that could be simple - run query x - if any rows are returned - send an email to predetermined person.
