### ISSUE TITLE
Use Distribution list for alerts, cert notification and uptime report

### ISSUE THREAD

**Issue by ArogeG** [bcgov/fsa2#72]
Please replace personal email with distribution list email for things like alerts, certs, and reports:

Distribution List: LWRS SIBI FSA-Fingerprints
Distribution email: SIBIFSAF@Victoria1.gov.bc.ca

Current members of the list include:

- derobert
- GATITEBI
- ptollest
- KJNether
- mrdouvil
- tagbaje
-

Let me know if anyone else should be added.

**Comment by ArogeG** [comment]
Distribution email has been created but failed test for emails from external organization. I have reached out to the i-store team to look into this.

**Comment by ArogeG** [comment]
Distribution list is all setup, please replace personal emails for alerts, certs, and other fingerprint project related notifications with SIBIFSAF@Victoria1.gov.bc.ca. This is the fingerprint distribution list email.  @DerekRoberts @explorertolu @franTarkenton

**Comment by DerekRoberts** [comment]
Resolved a while back.  Uptime robot is sending outage info exclusively to SIBIFSAF@Victoria1.gov.bc.ca.
